{
	'name':'Sitio Imagen',
  	'description': 'Sitio web para imagen',
  	'version':'1.0',
  	'author':'Imagen',
	'data': [
		'views/assets_imagen.xml',
		'views/headers.xml',
        'views/footer.xml',
        'views/shop_page.xml',
        'views/product.xml',
        'views/cart_page.xml',
        'views/sale.xml',
		'views/delivery.xml',
		'views/terms.xml',
		'views/contact.xml',
		'views/report_order.xml',
		'views/promo_code.xml',
		'views/kit_ludico_matematico.xml',
		'views/template_email.xml',
		'views/tmp_code_error.xml',
		'views/kit_leolandia.xml',
		'views/thanks_transfer.xml',
		'views/thanks.xml',
		'views/recommended_products.xml'
	],
  	'depends': [
		'website',
        'website_theme_install',
        'sale',
        'website_sale',
        'website_sale_delivery',
        'payment',
        'website_sale_coupon'
	],
}